### ISSUE TITLE
[Enhancement] Improve Perceived Performance

### ISSUE THREAD

**Issue by Secretmapper** [fcsonline/react-transmission#35]
Using the app, it seems that some operations are very slow, i.e. pausing a torrent can take more than a second, while the same thing on transmission-web instant.

- [] Issuing commands (play, pause, etc)
- [] Settings (Download Folder, Free space)

These two are the most obvious when I was using it, but hoping we can use this issue to list out all rpc-based/perceived performance problems.

**Comment by fcsonline** [comment]
All those operations are slow because we wait for the server to confirm that the action was performed successfully. To improve perceived performance, we can be optimistic in almost all the action a user does.

So, it's as simple as assume that an action is going to be performed successfully in all our stores and change the state before getting the server response.

What do you think? I think that could be a nice improvement.

**Comment by Secretmapper** [comment]
Yup, exactly! I think we could make everything optimistic.

I'll publish a PR when I have more free time.
